server:
  port: 8060

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #discovery server
      routes:
        - id: foo-service
          uri: lb://FOO-SERVICE  #uri: http://localhost:8080
          predicates:
            - Path=/foo/**
          filters:
            - RewritePath=/foo/v2/api-docs, /v2/api-docs
            - RewritePath=/foo/(?<path>.*), /hello/$\{path}
        - id: bar-service
          uri: lb://bar-service
          predicates:
            - Path=/bar/**
          filters:
            - RewritePath=/bar/(?.*), /$\{path}

#actuator
info:
  app:
    name: Gateway Server
    description: This is Gateway Server spring boot application
    version: 1.0.0

#Micrometer
management:
  endpoint:
    gateway:
      enabled: true # default value
  endpoints:
    web:
      exposure:
        include: '*' #gateway

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1


