server:
  port: 8060

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

#Actuator
info:
  app:
    name: GateWay Service

#Micrometr
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        exclude: '*' #or just gateway

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1


